Icons
DavidBlaa/kukuwi pull request #50
Opened 2024-12-03 17:00 UTC by Jennifer7283

Neue Icons eingefügt und skaliert

2024-12-03 18:03 UTC, JNYscript requested changes
sieht gut aus. Du müsstest allerdings die Icons nochmal für die /Demo Seite anpassen.

Evt. bei den Icons einen Rand hinzufügen. Ansonsten Kleben die Instrumente immer an der Border.

2024-12-03 20:16 UTC, dietrjo requested changes
Hab noch ein paar kleine Dinge am Code kommentiert, die ich noch ändern würde. Sonst alles super

2024-12-03 20:16 UTC, dietrjo commented on src/lib/components/Icons.svelte
> +    export let src;
$props rune von svelte benutzen

2024-12-03 20:16 UTC, dietrjo commented on src/lib/components/Icons.svelte
> +    }
tailwind verwenden

2024-12-03 20:16 UTC, dietrjo commented on src/lib/components/Icons.svelte
würde die Datei zu Icon.svelte umbenennen

2024-12-04 07:43 UTC, Jennifer7283 commented
Neue Icons eingefügt, skaliert

2024-12-04 07:43 UTC, merged