Merge Konflikte gelöst
DavidBlaa/kukuwi pull request #70
Opened 2024-12-21 11:09 UTC by Jennifer7283

2024-12-21 15:38 UTC, dietrjo commented
Nicht wundern warum ich was commited habe. Der Spieldurchlauf hat gerade nicht mehr ordentlich funktioniert nach unseren Änderungen und das habe ich jetzt schnell gefixt

2024-12-21 16:07 UTC, dietrjo requested changes
die paar Dinge, die ich jetzt noch kommentiert habe, sollten denke vor dem Abschluss des Issues noch geändert werden. Sag gerne bescheid, falls du bei was nicht verstehst, was ich meine :)

2024-12-21 16:07 UTC, dietrjo commented on src/lib/utils/helperfunctions.ts
> +import { base } from '$app/paths';
unused imports entfernen

2024-12-22 08:03 UTC, Jennifer7283 commented on src/lib/components/MenuCard.svelte
Der Inhalt ist jetzt wieder zentral und die anderen Dinge habe ich auch angepasst. Nur das mit dem 3D Effekt klappt immer noch nicht

2024-12-22 14:07 UTC, dietrjo commented on src/lib/components/MenuCard.svelte
wenn du deine Änderungen commitest, kann ichs mir gerne auch mal anschauen

2024-12-22 16:53 UTC, Jennifer7283 commented on src/lib/components/MenuCard.svelte
Hab ich, habe hoffentlich deine Kommentare richtig verstanden :D

2024-12-23 00:39 UTC, dietrjo commented on src/lib/components/MenuCard.svelte
ich hab es gefixt, kannst jetzt mergen

2024-12-23 08:44 UTC, merged